# This is a basic workflow to help you get started with Actions

name: Hello World

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Run pwd
        run: pwd

      - name: Run ls -al
        run: ls -al
